[package]
name = "artsy"
version = "0.1.0"
authors = ["Jean-Marie Comets <jean.marie.comets@gmail.com>"]
edition = "2018"

[dependencies]
take_mut = "0.2.2"

[features]
default = ["node4", "node16", "node48"]
no-simd = []
node4 = []
node16 = []
node48 = []

[profile.release]
debug = true
